// ─── Types ────────────────────────────────────────────────────────

export interface SeedCategory {
  name: string
  slug: string
  description?: string
  sortOrder: number
  children?: SeedCategory[]
}

export interface SeedProduct {
  name: string
  categorySlug: string
  price: number
  sku: string
  stockQuantity: number
  isPricePublic: boolean
  featured: boolean
  imageUrl: string
  imageAlt: string
}

export interface SeedSiteSettings {
  storeName: string
  whatsappNumber: string
  whatsappMessageTemplate: string
  currencySymbol: string
}

// ─── Site Settings ────────────────────────────────────────────────

export const siteSettings: SeedSiteSettings = {
  storeName: 'TecnoVitrina',
  whatsappNumber: '5491155551234',
  whatsappMessageTemplate:
    'Hola! Me interesa el producto "{productName}" ({price}). Lo vi en: {url}',
  currencySymbol: '$',
}

// ─── Categories ───────────────────────────────────────────────────

export const categories: SeedCategory[] = [
  {
    name: 'Celulares y Dispositivos Móviles',
    slug: 'celulares-y-dispositivos-moviles',
    description: 'Smartphones, tablets, smartwatches y accesorios para tus dispositivos móviles.',
    sortOrder: 1,
    children: [
      { name: 'Celulares & Accesorios', slug: 'celulares-accesorios', sortOrder: 1 },
      { name: 'Smartwatches y Accesorios', slug: 'smartwatches-accesorios', sortOrder: 2 },
      { name: 'Tablets y E-Readers', slug: 'tablets-e-readers', sortOrder: 3 },
    ],
  },
  {
    name: 'Audio y Sonido',
    slug: 'audio-y-sonido',
    description: 'Auriculares, parlantes, micrófonos y todo lo que necesitas para disfrutar tu música.',
    sortOrder: 2,
    children: [
      { name: 'Auriculares', slug: 'auriculares', sortOrder: 1 },
      { name: 'Speakers', slug: 'speakers', sortOrder: 2 },
      { name: 'Micrófonos y Accesorios', slug: 'microfonos-accesorios', sortOrder: 3 },
    ],
  },
  {
    name: 'Entretenimiento, Imagen y Gaming',
    slug: 'entretenimiento-imagen-gaming',
    description: 'Televisores, consolas de videojuegos, proyectores y todo para tu entretenimiento.',
    sortOrder: 3,
    children: [
      { name: 'Televisores', slug: 'televisores', sortOrder: 1 },
      { name: 'Consolas', slug: 'consolas', sortOrder: 2 },
      { name: 'Controles', slug: 'controles', sortOrder: 3 },
      { name: 'Juegos', slug: 'juegos', sortOrder: 4 },
      { name: 'Accesorios para Consolas', slug: 'accesorios-consolas', sortOrder: 5 },
      { name: 'Proyectores y Pantallas', slug: 'proyectores-pantallas', sortOrder: 6 },
      { name: 'Soportes para TV', slug: 'soportes-tv', sortOrder: 7 },
    ],
  },
  {
    name: 'Smart Home',
    slug: 'smart-home',
    description: 'Dispositivos inteligentes para tu hogar: seguridad, iluminación y control.',
    sortOrder: 4,
    children: [
      { name: 'Cámaras de Seguridad', slug: 'camaras-seguridad', sortOrder: 1 },
      { name: 'Cerraduras Digitales', slug: 'cerraduras-digitales', sortOrder: 2 },
      { name: 'Alarmas y Sensores', slug: 'alarmas-sensores', sortOrder: 3 },
      { name: 'Iluminación Conectada', slug: 'iluminacion-conectada', sortOrder: 4 },
      { name: 'Interruptores Inteligentes', slug: 'interruptores-inteligentes', sortOrder: 5 },
    ],
  },
  {
    name: 'Navegación y Movilidad Eléctrica',
    slug: 'navegacion-movilidad-electrica',
    description: 'Sistemas GPS y soluciones de navegación para vehículos.',
    sortOrder: 5,
    children: [
      { name: 'Sistemas de Navegación GPS', slug: 'sistemas-navegacion-gps', sortOrder: 1 },
    ],
  },
]

// ─── Products ─────────────────────────────────────────────────────
// Unsplash URLs use the format: https://images.unsplash.com/photo-{id}?w=800&q=80

export const products: SeedProduct[] = [
  // ── Celulares & Accesorios ──────────────────────────────────────
  {
    name: 'Samsung Galaxy S24 Ultra 256GB',
    categorySlug: 'celulares-accesorios',
    price: 1299,
    sku: 'VIT-CEL-001',
    stockQuantity: 15,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
    imageAlt: 'Samsung Galaxy S24 Ultra smartphone',
  },
  {
    name: 'iPhone 15 Pro Max 256GB',
    categorySlug: 'celulares-accesorios',
    price: 1199,
    sku: 'VIT-CEL-002',
    stockQuantity: 20,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80',
    imageAlt: 'iPhone 15 Pro Max',
  },
  {
    name: 'Google Pixel 8 Pro 128GB',
    categorySlug: 'celulares-accesorios',
    price: 899,
    sku: 'VIT-CEL-003',
    stockQuantity: 12,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80',
    imageAlt: 'Google Pixel smartphone',
  },
  {
    name: 'Xiaomi 14 Ultra 512GB',
    categorySlug: 'celulares-accesorios',
    price: 999,
    sku: 'VIT-CEL-004',
    stockQuantity: 8,
    isPricePublic: false,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80',
    imageAlt: 'Xiaomi smartphone',
  },

  // ── Smartwatches y Accesorios ───────────────────────────────────
  {
    name: 'Apple Watch Series 9 GPS 45mm',
    categorySlug: 'smartwatches-accesorios',
    price: 429,
    sku: 'VIT-SWT-001',
    stockQuantity: 25,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=800&q=80',
    imageAlt: 'Apple Watch Series 9',
  },
  {
    name: 'Samsung Galaxy Watch 6 Classic',
    categorySlug: 'smartwatches-accesorios',
    price: 349,
    sku: 'VIT-SWT-002',
    stockQuantity: 18,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80',
    imageAlt: 'Samsung Galaxy Watch',
  },
  {
    name: 'Garmin Venu 3 GPS',
    categorySlug: 'smartwatches-accesorios',
    price: 449,
    sku: 'VIT-SWT-003',
    stockQuantity: 10,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
    imageAlt: 'Garmin Venu smartwatch',
  },

  // ── Tablets y E-Readers ─────────────────────────────────────────
  {
    name: 'iPad Pro M4 11" 256GB',
    categorySlug: 'tablets-e-readers',
    price: 1099,
    sku: 'VIT-TAB-001',
    stockQuantity: 14,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    imageAlt: 'iPad Pro tablet',
  },
  {
    name: 'Samsung Galaxy Tab S9 Ultra',
    categorySlug: 'tablets-e-readers',
    price: 1199,
    sku: 'VIT-TAB-002',
    stockQuantity: 7,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&q=80',
    imageAlt: 'Samsung Galaxy Tab',
  },
  {
    name: 'Amazon Kindle Paperwhite 16GB',
    categorySlug: 'tablets-e-readers',
    price: 149,
    sku: 'VIT-TAB-003',
    stockQuantity: 30,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80',
    imageAlt: 'Amazon Kindle e-reader',
  },

  // ── Auriculares ─────────────────────────────────────────────────
  {
    name: 'Sony WH-1000XM5 Noise Cancelling',
    categorySlug: 'auriculares',
    price: 349,
    sku: 'VIT-AUR-001',
    stockQuantity: 22,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80',
    imageAlt: 'Sony WH-1000XM5 auriculares',
  },
  {
    name: 'AirPods Pro 2da Generación USB-C',
    categorySlug: 'auriculares',
    price: 249,
    sku: 'VIT-AUR-002',
    stockQuantity: 35,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80',
    imageAlt: 'AirPods Pro earbuds',
  },
  {
    name: 'Bose QuietComfort Ultra Earbuds',
    categorySlug: 'auriculares',
    price: 299,
    sku: 'VIT-AUR-003',
    stockQuantity: 16,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=800&q=80',
    imageAlt: 'Bose earbuds',
  },
  {
    name: 'Sennheiser Momentum 4 Wireless',
    categorySlug: 'auriculares',
    price: 379,
    sku: 'VIT-AUR-004',
    stockQuantity: 9,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80',
    imageAlt: 'Sennheiser auriculares over-ear',
  },

  // ── Speakers ────────────────────────────────────────────────────
  {
    name: 'JBL Charge 5 Bluetooth Portátil',
    categorySlug: 'speakers',
    price: 179,
    sku: 'VIT-SPK-001',
    stockQuantity: 28,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
    imageAlt: 'JBL Charge 5 speaker portátil',
  },
  {
    name: 'Sonos Era 300 WiFi Speaker',
    categorySlug: 'speakers',
    price: 449,
    sku: 'VIT-SPK-002',
    stockQuantity: 11,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
    imageAlt: 'Sonos speaker de alta fidelidad',
  },
  {
    name: 'Marshall Stanmore III Bluetooth',
    categorySlug: 'speakers',
    price: 379,
    sku: 'VIT-SPK-003',
    stockQuantity: 6,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1507646227500-4d389b0012be?w=800&q=80',
    imageAlt: 'Marshall speaker vintage',
  },

  // ── Micrófonos y Accesorios ─────────────────────────────────────
  {
    name: 'Blue Yeti X USB Profesional',
    categorySlug: 'microfonos-accesorios',
    price: 169,
    sku: 'VIT-MIC-001',
    stockQuantity: 14,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80',
    imageAlt: 'Blue Yeti micrófono USB',
  },
  {
    name: 'Shure MV7+ Podcast Microphone',
    categorySlug: 'microfonos-accesorios',
    price: 269,
    sku: 'VIT-MIC-002',
    stockQuantity: 8,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80',
    imageAlt: 'Shure micrófono podcast',
  },
  {
    name: 'HyperX QuadCast S RGB USB',
    categorySlug: 'microfonos-accesorios',
    price: 139,
    sku: 'VIT-MIC-003',
    stockQuantity: 20,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=800&q=80',
    imageAlt: 'HyperX micrófono gaming RGB',
  },

  // ── Televisores ─────────────────────────────────────────────────
  {
    name: 'Samsung OLED S90D 65" 4K Smart TV',
    categorySlug: 'televisores',
    price: 1799,
    sku: 'VIT-TV-001',
    stockQuantity: 5,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&q=80',
    imageAlt: 'Samsung OLED Smart TV 65 pulgadas',
  },
  {
    name: 'LG OLED C4 55" 4K 120Hz',
    categorySlug: 'televisores',
    price: 1499,
    sku: 'VIT-TV-002',
    stockQuantity: 7,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800&q=80',
    imageAlt: 'LG OLED TV en sala de estar',
  },
  {
    name: 'Sony Bravia XR A95L 55" QD-OLED',
    categorySlug: 'televisores',
    price: 2499,
    sku: 'VIT-TV-003',
    stockQuantity: 3,
    isPricePublic: false,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&q=80',
    imageAlt: 'Sony Bravia TV premium',
  },

  // ── Consolas ────────────────────────────────────────────────────
  {
    name: 'PlayStation 5 Slim 1TB',
    categorySlug: 'consolas',
    price: 499,
    sku: 'VIT-CON-001',
    stockQuantity: 10,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&q=80',
    imageAlt: 'PlayStation 5 consola',
  },
  {
    name: 'Xbox Series X 1TB',
    categorySlug: 'consolas',
    price: 499,
    sku: 'VIT-CON-002',
    stockQuantity: 8,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800&q=80',
    imageAlt: 'Xbox Series X consola',
  },
  {
    name: 'Nintendo Switch OLED 64GB',
    categorySlug: 'consolas',
    price: 349,
    sku: 'VIT-CON-003',
    stockQuantity: 15,
    isPricePublic: true,
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&q=80',
    imageAlt: 'Nintendo Switch OLED',
  },

  // ── Controles ───────────────────────────────────────────────────
  {
    name: 'DualSense PS5 Edición Midnight Black',
    categorySlug: 'controles',
    price: 69,
    sku: 'VIT-CTR-001',
    stockQuantity: 40,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&q=80',
    imageAlt: 'DualSense PS5 control negro',
  },
  {
    name: 'Xbox Elite Wireless Controller Series 2',
    categorySlug: 'controles',
    price: 179,
    sku: 'VIT-CTR-002',
    stockQuantity: 12,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&q=80',
    imageAlt: 'Xbox Elite controller',
  },
  {
    name: 'Nintendo Switch Pro Controller',
    categorySlug: 'controles',
    price: 69,
    sku: 'VIT-CTR-003',
    stockQuantity: 25,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1585620385456-4a0a5e906ece?w=800&q=80',
    imageAlt: 'Nintendo Switch Pro controller',
  },

  // ── Juegos ──────────────────────────────────────────────────────
  {
    name: 'The Legend of Zelda: Tears of the Kingdom',
    categorySlug: 'juegos',
    price: 59,
    sku: 'VIT-JUE-001',
    stockQuantity: 50,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80',
    imageAlt: 'Videojuego Zelda',
  },
  {
    name: 'God of War Ragnarök PS5',
    categorySlug: 'juegos',
    price: 49,
    sku: 'VIT-JUE-002',
    stockQuantity: 35,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800&q=80',
    imageAlt: 'God of War videojuego',
  },
  {
    name: 'Hogwarts Legacy Xbox Series X',
    categorySlug: 'juegos',
    price: 39,
    sku: 'VIT-JUE-003',
    stockQuantity: 28,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&q=80',
    imageAlt: 'Hogwarts Legacy videojuego',
  },

  // ── Accesorios para Consolas ────────────────────────────────────
  {
    name: 'Headset Inalámbrico PlayStation Pulse 3D',
    categorySlug: 'accesorios-consolas',
    price: 99,
    sku: 'VIT-ACC-001',
    stockQuantity: 18,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=800&q=80',
    imageAlt: 'PlayStation Pulse 3D headset',
  },
  {
    name: 'Base de Carga DualSense PS5',
    categorySlug: 'accesorios-consolas',
    price: 29,
    sku: 'VIT-ACC-002',
    stockQuantity: 45,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1625805866449-3589fe3f71a3?w=800&q=80',
    imageAlt: 'Base de carga PS5',
  },
  {
    name: 'SSD Western Digital 1TB para PS5',
    categorySlug: 'accesorios-consolas',
    price: 89,
    sku: 'VIT-ACC-003',
    stockQuantity: 22,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&q=80',
    imageAlt: 'SSD disco para consola',
  },

  // ── Proyectores y Pantallas ─────────────────────────────────────
  {
    name: 'Epson Home Cinema 2350 4K PRO-UHD',
    categorySlug: 'proyectores-pantallas',
    price: 999,
    sku: 'VIT-PRO-001',
    stockQuantity: 4,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80',
    imageAlt: 'Epson proyector 4K',
  },
  {
    name: 'XGIMI Horizon Ultra 4K Proyector Láser',
    categorySlug: 'proyectores-pantallas',
    price: 1699,
    sku: 'VIT-PRO-002',
    stockQuantity: 3,
    isPricePublic: false,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1626379953822-baec19c3accd?w=800&q=80',
    imageAlt: 'XGIMI proyector láser',
  },
  {
    name: 'Pantalla de Proyección 120" Motorizada',
    categorySlug: 'proyectores-pantallas',
    price: 299,
    sku: 'VIT-PRO-003',
    stockQuantity: 8,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800&q=80',
    imageAlt: 'Pantalla de proyección motorizada',
  },

  // ── Soportes para TV ────────────────────────────────────────────
  {
    name: 'Soporte de Pared Articulado 32"-70"',
    categorySlug: 'soportes-tv',
    price: 49,
    sku: 'VIT-SOP-001',
    stockQuantity: 35,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80',
    imageAlt: 'Soporte de pared para TV',
  },
  {
    name: 'Soporte de Piso con Ruedas para TV 50"-85"',
    categorySlug: 'soportes-tv',
    price: 129,
    sku: 'VIT-SOP-002',
    stockQuantity: 12,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    imageAlt: 'Soporte móvil para TV',
  },
  {
    name: 'Soporte de Escritorio Dual Monitor',
    categorySlug: 'soportes-tv',
    price: 79,
    sku: 'VIT-SOP-003',
    stockQuantity: 20,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80',
    imageAlt: 'Soporte dual monitor escritorio',
  },

  // ── Cámaras de Seguridad ────────────────────────────────────────
  {
    name: 'Ring Video Doorbell Pro 2',
    categorySlug: 'camaras-seguridad',
    price: 249,
    sku: 'VIT-CAM-001',
    stockQuantity: 15,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80',
    imageAlt: 'Ring timbre con cámara',
  },
  {
    name: 'Arlo Pro 5 Cámara WiFi 2K',
    categorySlug: 'camaras-seguridad',
    price: 199,
    sku: 'VIT-CAM-002',
    stockQuantity: 20,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80',
    imageAlt: 'Arlo cámara seguridad exterior',
  },
  {
    name: 'Google Nest Cam Interior/Exterior',
    categorySlug: 'camaras-seguridad',
    price: 179,
    sku: 'VIT-CAM-003',
    stockQuantity: 18,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80',
    imageAlt: 'Google Nest cámara',
  },

  // ── Cerraduras Digitales ────────────────────────────────────────
  {
    name: 'August Wi-Fi Smart Lock 4ta Gen',
    categorySlug: 'cerraduras-digitales',
    price: 229,
    sku: 'VIT-CER-001',
    stockQuantity: 10,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    imageAlt: 'August cerradura inteligente',
  },
  {
    name: 'Yale Assure Lock 2 Touchscreen',
    categorySlug: 'cerraduras-digitales',
    price: 279,
    sku: 'VIT-CER-002',
    stockQuantity: 8,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80',
    imageAlt: 'Yale cerradura táctil',
  },
  {
    name: 'Schlage Encode Plus Smart Deadbolt',
    categorySlug: 'cerraduras-digitales',
    price: 299,
    sku: 'VIT-CER-003',
    stockQuantity: 6,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80',
    imageAlt: 'Schlage cerradura electrónica',
  },

  // ── Alarmas y Sensores ──────────────────────────────────────────
  {
    name: 'Ring Alarm Kit 8 Piezas 2da Gen',
    categorySlug: 'alarmas-sensores',
    price: 249,
    sku: 'VIT-ALR-001',
    stockQuantity: 12,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80',
    imageAlt: 'Ring sistema de alarma',
  },
  {
    name: 'Sensor de Movimiento Philips Hue',
    categorySlug: 'alarmas-sensores',
    price: 39,
    sku: 'VIT-ALR-002',
    stockQuantity: 30,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    imageAlt: 'Philips Hue sensor de movimiento',
  },
  {
    name: 'Detector de Humo Nest Protect',
    categorySlug: 'alarmas-sensores',
    price: 119,
    sku: 'VIT-ALR-003',
    stockQuantity: 15,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80',
    imageAlt: 'Nest Protect detector de humo',
  },

  // ── Iluminación Conectada ───────────────────────────────────────
  {
    name: 'Philips Hue Starter Kit 3 Bombillas E27',
    categorySlug: 'iluminacion-conectada',
    price: 129,
    sku: 'VIT-ILU-001',
    stockQuantity: 20,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80',
    imageAlt: 'Philips Hue kit de iluminación',
  },
  {
    name: 'LIFX Tira LED Multicolor 2m WiFi',
    categorySlug: 'iluminacion-conectada',
    price: 79,
    sku: 'VIT-ILU-002',
    stockQuantity: 25,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1550985543-49bee3167284?w=800&q=80',
    imageAlt: 'Tira LED RGB inteligente',
  },
  {
    name: 'Nanoleaf Shapes Hexagons Kit 9 Paneles',
    categorySlug: 'iluminacion-conectada',
    price: 199,
    sku: 'VIT-ILU-003',
    stockQuantity: 10,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    imageAlt: 'Nanoleaf paneles decorativos LED',
  },

  // ── Interruptores Inteligentes ──────────────────────────────────
  {
    name: 'TP-Link Kasa Smart Switch HS200',
    categorySlug: 'interruptores-inteligentes',
    price: 19,
    sku: 'VIT-INT-001',
    stockQuantity: 50,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80',
    imageAlt: 'TP-Link interruptor inteligente',
  },
  {
    name: 'Lutron Caseta Dimmer Starter Kit',
    categorySlug: 'interruptores-inteligentes',
    price: 99,
    sku: 'VIT-INT-002',
    stockQuantity: 15,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80',
    imageAlt: 'Lutron dimmer inteligente',
  },
  {
    name: 'Enchufe Inteligente WiFi Amazon Smart Plug',
    categorySlug: 'interruptores-inteligentes',
    price: 24,
    sku: 'VIT-INT-003',
    stockQuantity: 40,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    imageAlt: 'Amazon Smart Plug enchufe inteligente',
  },

  // ── Sistemas de Navegación GPS ──────────────────────────────────
  {
    name: 'Garmin DriveSmart 76 GPS 7"',
    categorySlug: 'sistemas-navegacion-gps',
    price: 299,
    sku: 'VIT-GPS-001',
    stockQuantity: 10,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1476973422084-e0fa66ff9456?w=800&q=80',
    imageAlt: 'Garmin DriveSmart navegador GPS',
  },
  {
    name: 'TomTom GO Expert 7" Camiones',
    categorySlug: 'sistemas-navegacion-gps',
    price: 399,
    sku: 'VIT-GPS-002',
    stockQuantity: 5,
    isPricePublic: true,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    imageAlt: 'TomTom GPS navegador',
  },
  {
    name: 'Garmin Overlander GPS Todo Terreno',
    categorySlug: 'sistemas-navegacion-gps',
    price: 699,
    sku: 'VIT-GPS-003',
    stockQuantity: 3,
    isPricePublic: false,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80',
    imageAlt: 'Garmin Overlander GPS todoterreno',
  },
]
